//Get Super Usuario
export const GET_SUPERUSER_REQUEST = 'GET_SUPERUSER_REQUEST';
export const GET_SUPERUSER_SUCCESS = 'GET_SUPERUSER_SUCCESS';
export const GET_SUPERUSER_FAILURE = 'GET_SUPERUSER_FAILURE';
//Post Super Usuario
export const POST_SUPERUSER_REQUEST = 'POST_SUPERUSER_REQUEST';
export const POST_SUPERUSER_SUCCESS = 'POST_SUPERUSER_SUCCESS';
export const POST_SUPERUSER_FAILURE = 'POST_SUPERUSER_FAILURE';
//Delete Super Usuario
export const DELETE_SUPERUSER_REQUEST = 'DELETE_SUPERUSER_REQUEST';
export const DELETE_SUPERUSER_SUCCESS = 'DELETE_SUPERUSER_SUCCESS';
export const DELETE_SUPERUSER_FAILURE = 'DELETE_SUPERUSER_FAILURE';
//Put Super Usuario
export const PUT_SUPERUSER_REQUEST = 'PUT_SUPERUSER_REQUEST';
export const PUT_SUPERUSER_SUCCESS = 'PUT_SUPERUSER_SUCCESS';
export const PUT_SUPERUSER_FAILURE = 'PUT_SUPERUSER_FAILURE';


//Get Business
export const GET_BUSINESS_REQUEST = 'GET_BUSINESS_REQUEST';
export const GET_BUSINESS_SUCCESS = 'GET_BUSINESS_SUCCESS';
export const GET_BUSINESS_FAILURE = 'GET_BUSINESS_FAILURE';
//Post Business
export const CREATE_BUSINESS_REQUEST = 'CREATE_BUSINESS_REQUEST';
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS';
export const CREATE_BUSINESS_FAILURE = 'CREATE_BUSINESS_FAILURE';