//Get Super Usuario
export const GET_SUPERUSER_REQUEST = 'GET_SUPERUSER_REQUEST';
export const GET_SUPERUSER_SUCCESS = 'GET_SUPERUSER_SUCCESS';
export const GET_SUPERUSER_FAILURE = 'GET_SUPERUSER_FAILURE';
//Post Super Usuario
export const POST_SUPERUSER_REQUEST = 'POST_SUPERUSER_REQUEST';
export const POST_SUPERUSER_SUCCESS = 'POST_SUPERUSER_SUCCESS';
export const POST_SUPERUSER_FAILURE = 'POST_SUPERUSER_FAILURE';
//Delete Super Usuario
export const DELETE_SUPERUSER_REQUEST = 'DELETE_SUPERUSER_REQUEST';
export const DELETE_SUPERUSER_SUCCESS = 'DELETE_SUPERUSER_SUCCESS';
export const DELETE_SUPERUSER_FAILURE = 'DELETE_SUPERUSER_FAILURE';
//Put Super Usuario
export const PUT_SUPERUSER_REQUEST = 'PUT_SUPERUSER_REQUEST';
export const PUT_SUPERUSER_SUCCESS = 'PUT_SUPERUSER_SUCCESS';
export const PUT_SUPERUSER_FAILURE = 'PUT_SUPERUSER_FAILURE';